spring.application.name=ExemploCarros


#Banco de dados
spring.datasource.url=jdbc:mariadb://localhost:3306/exemplo_carros?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=user
spring.datasource.password=senha123

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none

#liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml